// Has to be regenerated by calling the regen proc manually, elsewhere.
/obj/item/clothing/suit/roguetown/armor/manual
	name = "manually regenerating skin"
	break_sound = 'sound/foley/cloth_rip.ogg'
	drop_sound = 'sound/foley/dropsound/cloth_drop.ogg'
	icon_state = null
	slot_flags = ITEM_SLOT_SHIRT|ITEM_SLOT_ARMOR

	resistance_flags = FIRE_PROOF
	body_parts_covered = COVERAGE_FULL
	body_parts_inherent = COVERAGE_FULL
	flags_inv = null //Exposes the chest and-or breasts.
	surgery_cover = FALSE //Should permit surgery and other invasive processes.
	r_sleeve_status = SLEEVE_NORMAL
	l_sleeve_status = SLEEVE_NORMAL
	armor_class = ARMOR_CLASS_LIGHT
	blocksound = SOFTUNDERHIT
	armor = ARMOR_PADDED
	unenchantable = TRUE

	var/repairmsg_end = "My skin has become taut with newfound vigor!"
	var/repairmsg_continue = "My armour mends some of its abuse.."

/obj/item/clothing/suit/roguetown/armor/manual/Initialize(mapload)
	..()
	ADD_TRAIT(src, TRAIT_NODROP, CURSED_ITEM_TRAIT)

/obj/item/clothing/suit/roguetown/armor/manual/dropped(mob/living/carbon/human/user)
	..()
	if(QDELETED(src))
		return
	qdel(src)

/obj/item/clothing/suit/roguetown/armor/manual/proc/armour_regen(var/repair_percent = 0.35 * max_integrity)
    if(obj_integrity >= max_integrity)
        to_chat(loc, span_notice(repairmsg_end))
    to_chat(loc, span_notice(repairmsg_continue))
    obj_integrity = min(obj_integrity + repair_percent, max_integrity)
    if(obj_broken)
        obj_fix(full_repair = FALSE)

//35% repair per proc, procs taking ~10-11s for sewing, pushup set, or meditation emote. Thus ~30-33s to fullrepair.



/*
 * PUSHUP ARMOUR
 */

/obj/item/clothing/suit/roguetown/armor/manual/pushups
    name = "muscular skin"
    desc = "The reward for all your hard work. </br>THE INFLUENCE OF THE HAM SANDWYCH RACE IS WANING. I MUST DO PUSH-UPS, TO REMIND MY MUSCLES OF THEIR OWN STRENGTH."

    repairmsg_end = "My muscles sheen with vitality!"
    repairmsg_continue = "My muscles are reminded of their own strength."

/obj/item/clothing/suit/roguetown/armor/manual/pushups/get_mechanics_examine(mob/user)
	. = ..()

	. += span_info("Repairable via push-up emotes.")


/obj/item/clothing/suit/roguetown/armor/manual/pushups/barbarian
	armor = ARMOR_LEATHER
	max_integrity = ARMOR_INT_CHEST_LIGHT_MASTER //Identical to a glued-on hardened leather coat, with bonus arm-hand-foot coverage.

/*
 * MEDITATION ARMOUR - Currently no trigger for the repair proc, thus unused and should not be used.
 */

/obj/item/clothing/suit/roguetown/armor/manual/meditation
    name = "harmonious skin"
    desc = "Exotic skin armor that can be renewed via meditation. If you see this ingame, something went wrong."

/obj/item/clothing/suit/roguetown/armor/manual/meditation/get_mechanics_examine(mob/user)
	. = ..()

	. += span_info("Repairable via meditate emotes.")

/obj/item/clothing/suit/roguetown/armor/manual/meditation/easttats
	resistance_flags = FIRE_PROOF
	icon_state = "easttats"
	body_parts_covered = COVERAGE_FULL | COVERAGE_HEAD //This does not cover eyes/nose/mouth/neck.
	body_parts_inherent = COVERAGE_FULL | COVERAGE_HEAD
	icon = 'icons/roguetown/clothing/shirts.dmi'
	mob_overlay_icon = 'icons/roguetown/clothing/onmob/shirts.dmi'
	sleeved = 'icons/roguetown/clothing/onmob/helpers/sleeves_shirts.dmi'
	//allowed_race = NON_DWARVEN_RACE_TYPES

	repairmsg_end = "The tattoos flow more calmly, as the meditation renews their strength."
	repairmsg_continue = "The tattoos mend some of their abuse..."

/obj/item/clothing/suit/roguetown/armor/manual/meditation/easttats/ruma
	name = "bouhoi bujeog tattoos"
	desc = "A mystic style of tattoos adopted by the Ruma Clan, emulating a practice performed by warrior monks of the Xinyi Dynasty. They are your way of identifying fellow clan members, a sign of companionship and secretive brotherhood. These are styled into the shape of clouds, created by a mystical ink which shifts and moves in ripples like a pond to harden where your skin is struck. Its movement causes you to shudder, and meditation restores its strength."
	armor = ARMOR_PLATE //Great defence, while it lasts.
	max_integrity = ARMOR_INT_CHEST_PLATE_BRIGANDINE //1.17x integrity (350) vs baseline skin armor (300).
	//Perk of being a mercenary kinda-powerclass, and dealing with the Honorbound restrictions (no metal armor, no gambesons).

/obj/item/clothing/suit/roguetown/armor/manual/meditation/easttats/mistwalker
	name = "seon-mul tattoos"
	desc = "The flowing clouds of the Ruma are but fleeting shadow across the plains, pale imitation of Xinyi's spiritual alchemy. Imperfect, impotent. Their legend is one writ in avarice and hate.</br></br>Recount yours in love."
	armor = ARMOR_LEATHER
	max_integrity = ARMOR_INT_CHEST_LIGHT_MASTER + 150 //1.5x integrity (450) vs baseline leather skin armor (300).
	//Perk of being a wretch powerclass, and dealing with the Honorbound restrictions (no metal armor, no gambesons).


/*
 * SEWABLE ARMOUR
 */

/obj/item/clothing/suit/roguetown/armor/manual/sewable
	var/list/repair_items[] = list(
		/obj/item/needle = 'sound/foley/sewflesh.ogg',
		/obj/item/needle/thorn = 'sound/foley/sewflesh.ogg',
		/obj/item/needle/bronze = 'sound/foley/sewflesh.ogg',
		/obj/item/needle/pestra = 'sound/foley/sewflesh.ogg'
	)

/obj/item/clothing/suit/roguetown/armor/manual/sewable/get_mechanics_examine(mob/user)
	. = ..()

	for(var/repair_thing in repair_items)
		var/obj/item/thing = new repair_thing
		. += span_info("Repairable via [thing.name].")

/obj/item/clothing/suit/roguetown/armor/manual/sewable/attackby(obj/item/I, mob/user, params)
	if(user != loc)
		return FALSE
	if(obj_integrity == max_integrity)
		to_chat(user, span_warning("My skin isn't wounded."))
		return FALSE
	if(!repair_check(user, I))
		return FALSE

	if(!do_after(user, 10 SECONDS, target = src))
		return FALSE

	armour_regen()

	playsound(loc, repair_items[I.type], 100, TRUE)
	return TRUE

/obj/item/clothing/suit/roguetown/armor/manual/sewable/proc/repair_check(mob/user, obj/item/I)
	if(!(I.type in repair_items))
		return FALSE

	if(istype(I, /obj/item/needle))
		var/obj/item/needle/sew_needle = I
		if(!sew_needle.stringamt)
			to_chat(user, span_warning("[src] has no thread!"))
			return FALSE

	return TRUE

/obj/item/clothing/suit/roguetown/armor/manual/sewable/repair_check(mob/user, obj/item/I)
	. = ..()

	if(!.)
		return FALSE

	if(istype(I, /obj/item/rogueweapon/surgery/cautery))
		var/obj/item/rogueweapon/surgery/cautery/sew_cautery = I
		if(!sew_cautery.heated)
			to_chat(user, span_warning("[src] is not heated up!"))
			return FALSE

	return TRUE



//PADDED
/obj/item/clothing/suit/roguetown/armor/manual/sewable/padded
	name = "sewable skin armor"
	desc = "This should not spawn naturally. If you see this ingame, something went wrong."
	armor = ARMOR_PADDED
	max_integrity = ARMOR_INT_CHEST_LIGHT_MEDIUM //Identical to a glued-on gambeson in armor slot, with bonus hand+foot coverage.
	repair_items = list(
		/obj/item/needle = 'sound/foley/sewflesh.ogg',
		/obj/item/needle/thorn = 'sound/foley/sewflesh.ogg',
		/obj/item/needle/bronze = 'sound/foley/sewflesh.ogg',
		/obj/item/needle/pestra = 'sound/foley/sewflesh.ogg',
		/obj/item/rogueweapon/surgery/cautery = 'sound/surgery/cautery1.ogg'
	)

/obj/item/clothing/suit/roguetown/armor/manual/sewable/padded/barbarian
	name = "hardened skin"
	desc = "Toughened from abuse. My mettle remains."

/obj/item/clothing/suit/roguetown/armor/manual/sewable/padded/gladiator
	name = "pit-hardened skin"
	desc = "Are you not entertained?!"

/obj/item/clothing/suit/roguetown/armor/manual/sewable/padded/bailiff
	name = "scar-marred skin"
	desc = "Bearing scars of countless whips leaves a gnarly visage. Now it's your time to inflict the same fate upon others."
	max_integrity = ARMOR_INT_CHEST_LIGHT_MASTER //1.2x integrity (300) vs baseline padded skin armor (250).
	//Perk of being a MAA kinda-powerclass. Basically just a heavy gambeson.

/obj/item/clothing/suit/roguetown/armor/manual/sewable/padded/monke
	name = "trained skin"
	desc = "They say I've taken the first step on a path older than memory.\
	</br>Aeon, Psydon, Adonai… I don't fully understand what those names mean yet, but I repeat them as I was taught.\
	</br>The world is said to be held together by His sacrifice. I can't imagine something like that, but the Disciples say it is true.\
	</br>I came here because I wanted purpose, something solid to believe in.\
	</br>They tell me doubt is natural, and that understanding comes with time.\
	</br>For now, I will listen, learn, and try to live in a way that does not waste what was given to us."

/obj/item/clothing/suit/roguetown/armor/manual/sewable/padded/monk
	name = "tough skin"
	desc = "Do you forsake protection for enlightenment, or in repentance for past transgressions?"
	max_integrity = ARMOR_INT_CHEST_LIGHT_BASE //0.8x integrity (200) vs baseline padded skin armor (250).
	//Tax for being an advent with utility miracles.

/obj/item/clothing/suit/roguetown/armor/manual/sewable/padded/confessor
	name = "arbalist's skin"
	desc = "Taut lyke the bow I draw."
	max_integrity = ARMOR_INT_CHEST_LIGHT_BASE //0.8x integrity (200) vs baseline padded skin armor (250).
	//Tax for being shirt slot.

/obj/item/clothing/suit/roguetown/armor/manual/sewable/padded/disciple
	name = "enduring skin"
	desc = "It's far more than just an oath. \
	</br>Aeon, Psydon, Adonai. Entropy, Humenity, Divinity; a trinity known to all, yet forgotten to tyme. \
	</br>A corpse. I am living on a fucking corpse. He is the world, and the world is rotting away. \
	</br>To give into despair and hopelessness, however, is to rob all meaning from His sacrifice. \
	</br>Heaven's gate closed to us long ago, yet His children persist; as as long as they do, so must I. \
	</br>Happiness must be fought for."
	max_integrity = ARMOR_INT_CHEST_LIGHT_MASTER + 100 //1.6x integrity (400) vs baseline padded skin armor (250).
	//Perk of being a psy-templar powerclass.


//LEATHER
/obj/item/clothing/suit/roguetown/armor/manual/sewable/leather
	name = "sewable skin armor"
	desc = "This should not spawn naturally. If you see this ingame, something went wrong."
	armor = ARMOR_LEATHER
	max_integrity = ARMOR_INT_CHEST_LIGHT_MASTER //Identical to a glued-on hardened leather coat, with bonus arm-hand-foot coverage.
	repair_items = list(
		/obj/item/needle = 'sound/foley/sewflesh.ogg',
		/obj/item/needle/thorn = 'sound/foley/sewflesh.ogg',
		/obj/item/needle/bronze = 'sound/foley/sewflesh.ogg',
		/obj/item/needle/pestra = 'sound/foley/sewflesh.ogg',
		/obj/item/rogueweapon/surgery/cautery = 'sound/surgery/cautery1.ogg'
	)

/obj/item/clothing/suit/roguetown/armor/manual/sewable/leather/berzerker
	name = "unstoppable skin"
	desc = "I've endured enough. The onslaught has lost its meaning."
	blocking_behavior = SAMEWEAR
	slot_flags = ITEM_SLOT_ARMOR|ITEM_SLOT_SHIRT
	max_integrity = ARMOR_INT_CHEST_LIGHT_MASTER + 150 //1.5x integrity (450) vs baseline leather skin armor (300).
	//Perk of being a wretch powerclass.


//MAILLE
/obj/item/clothing/suit/roguetown/armor/manual/sewable/maille
	name = "sewable skin armor"
	desc = "This should not spawn naturally. If you see this ingame, something went wrong."
	armor = ARMOR_MAILLE
	max_integrity = ARMOR_INT_CHEST_LIGHT_IRON
	repair_items = list(
		/obj/item/needle = 'sound/foley/sewflesh.ogg',
		/obj/item/needle/thorn = 'sound/foley/sewflesh.ogg',
		/obj/item/needle/bronze = 'sound/foley/sewflesh.ogg',
		/obj/item/needle/pestra = 'sound/foley/sewflesh.ogg',
		/obj/item/rogueweapon/surgery/cautery = 'sound/surgery/cautery1.ogg'
	)

/obj/item/clothing/suit/roguetown/armor/manual/sewable/maille/berzerkerchest
	name = "unstoppable chest"
	desc = "The callouses could stop arrows! But only so many."
	slot_flags = ITEM_SLOT_ARMOR
	armor = ARMOR_MAILLE
	resistance_flags = FLAMMABLE
	blocksound = SOFTHIT
	blocking_behavior = SAMEWEAR
	body_parts_covered = COVERAGE_VEST
	body_parts_inherent = COVERAGE_VEST